user_input=input("enter your name:")
course_input=input("enter your course name:")
DOB=input("enter your date of birth:")
uni_roll=int(input("enter your roll no.:"))
sess_no=input("enter the session year:")
lib_code=input("enter your library code:")
pon_input=int(input("enter your phone number:"))
print("\n"*2)
print("name-",user_input)
print("course:",course_input)
print("date-of-birth:",DOB)
print("university roll no.:",uni_roll)
print("session:",sess_no)
print("library code:",lib_code)
print("phone no.",pon_input)
